Creating a more user-friendly interface
StanislavBeliaev/DIMS pull request #25
Opened 2022-11-02 10:50 UTC by StanislavBeliaev

Now when you create a new user, form will give you a messages if you did something wrong.Burger menu was added for easier site navigation.Logout button was added.

2022-11-10 08:04 UTC, YauhenKoipish requested changes

2022-11-10 08:04 UTC, YauhenKoipish commented on src/pages/MemberTasks.jsx
> +                {userData.map(([id, val], idx) => {
I think here we can avoid using map

2022-11-17 22:47 UTC, StanislavBeliaev commented
Added secure routes, burger menu is not available if you are not logged in

2022-11-17 23:28 UTC, StanislavBeliaev commented on src/App/App.jsx
> +    console.log(burgerStatus);
done

2022-11-17 23:28 UTC, StanislavBeliaev commented on src/App/App.jsx
> +                        </svg>
done

2022-11-17 23:28 UTC, StanislavBeliaev commented on src/App/App.jsx
> +                                        />
done

2022-11-17 23:28 UTC, StanislavBeliaev commented on src/App/App.jsx
> +                                    </svg>
done

2022-11-17 23:28 UTC, StanislavBeliaev commented on src/pages/LoginPage.jsx
>                  console.log(userCredential);
done

2022-11-17 23:29 UTC, StanislavBeliaev commented on src/pages/LoginPage.jsx
> +                                    </svg>
done

2022-11-17 23:29 UTC, StanislavBeliaev commented on src/pages/LoginPage.jsx
> +                                    </svg>
done

2022-11-17 23:29 UTC, StanislavBeliaev commented on src/pages/MemberTasks.jsx
> +                {userData.map(([id, val], idx) => {
done

2022-12-02 13:19 UTC, merged